# Header
menu:
  Home: /
  Archives: /archives/

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
- archive

# widget behavior
archive_type: monthly
show_count: true

favicon: /favicon.png

service_worker: true
manifest: true
banner:
  pc: /img/banner-pc.jpg
  mobile: /img/banner-mobile.jpg
